// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Category struct {
	ID   int32
	Name string
}

type Transaction struct {
	ID          int32
	Date        time.Time
	Description string
	Amount      float64
	Notes       sql.NullString
	CategoryID  int32
}
