// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Transaction struct {
	ID          uuid.UUID
	Date        time.Time
	Description string
	Amount      float64
	Category    string
	Notes       sql.NullString
}
