// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    date, description, amount, notes, category_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, date, description, amount, notes, category_id
`

type CreateTransactionParams struct {
	Date        time.Time
	Description string
	Amount      float64
	Notes       sql.NullString
	CategoryID  int32
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.Date,
		arg.Description,
		arg.Amount,
		arg.Notes,
		arg.CategoryID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Description,
		&i.Amount,
		&i.Notes,
		&i.CategoryID,
	)
	return i, err
}

const deleteAllTransactions = `-- name: DeleteAllTransactions :exec
DELETE FROM transactions
`

func (q *Queries) DeleteAllTransactions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllTransactions)
	return err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const getAllTransactions = `-- name: GetAllTransactions :many
SELECT t.id, t.date, t.description, t.amount, t.notes, c.name AS category
FROM transactions AS t
JOIN categories AS c ON t.category_id = c.id
`

type GetAllTransactionsRow struct {
	ID          int32
	Date        time.Time
	Description string
	Amount      float64
	Notes       sql.NullString
	Category    string
}

func (q *Queries) GetAllTransactions(ctx context.Context) ([]GetAllTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTransactionsRow
	for rows.Next() {
		var i GetAllTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Description,
			&i.Amount,
			&i.Notes,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateCategory = `-- name: GetOrCreateCategory :one
WITH existing_category AS (
    SELECT id FROM categories WHERE categories.name = $1
),
inserted_category AS (
    INSERT INTO categories (name)
    SELECT $1
    WHERE NOT EXISTS (SELECT 1 FROM existing_category)
    RETURNING id
)
SELECT id FROM existing_category
UNION ALL
SELECT id FROM inserted_category
`

func (q *Queries) GetOrCreateCategory(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateCategory, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getTransactionById = `-- name: GetTransactionById :one
SELECT t.id, t.date, t.description, t.amount, t.notes, c.name AS category
FROM transactions AS t
JOIN categories AS c ON t.category_id = c.id
WHERE t.id = $1
`

type GetTransactionByIdRow struct {
	ID          int32
	Date        time.Time
	Description string
	Amount      float64
	Notes       sql.NullString
	Category    string
}

func (q *Queries) GetTransactionById(ctx context.Context, id int32) (GetTransactionByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionById, id)
	var i GetTransactionByIdRow
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Description,
		&i.Amount,
		&i.Notes,
		&i.Category,
	)
	return i, err
}

const getTransactionsByCategory = `-- name: GetTransactionsByCategory :many
SELECT t.id, t.date, t.description, t.amount, t.notes, c.name AS category
FROM transactions AS t
JOIN categories AS c ON t.category_id = c.id
WHERE c.name = $1
`

type GetTransactionsByCategoryRow struct {
	ID          int32
	Date        time.Time
	Description string
	Amount      float64
	Notes       sql.NullString
	Category    string
}

func (q *Queries) GetTransactionsByCategory(ctx context.Context, name string) ([]GetTransactionsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByCategory, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsByCategoryRow
	for rows.Next() {
		var i GetTransactionsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Description,
			&i.Amount,
			&i.Notes,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
