GET http://localhost:8080/

###

GET http://localhost:8080/api/transactions

###

GET http://localhost:8080/api/transactions/4

###

GET http://localhost:8080/api/transactions?category=Groceries

###

POST http://localhost:8080/api/transactions
content-type: application/json

{
    "date": "2025-12-01T00:00:00Z",
    "description": "Nenya",
    "amount": 2000.00,
    "category": "Gifts",
    "notes": "Christmas present"
}

###

GET http://localhost:8080/api/categories

###

DELETE http://localhost:8080/api/transactions/4