GET http://localhost:8080/

###

GET http://localhost:8080/api/transactions

###

GET http://localhost:8080/api/transactions/1

###

GET http://localhost:8080/api/transactions?category=Groceries

###

POST http://localhost:8080/api/transactions
content-type: application/json

{
    "date": "2025-12-01T00:00:00Z",
    "description": "Nenya",
    "amount": 2000.00,
    "category": "Gifts",
    "notes": "Christmas present"
}

###

GET http://localhost:8080/api/categories

###

DELETE http://localhost:8080/api/transactions/4

###

PUT http://localhost:8080/api/transactions/4
content-type: application/json

{
    "date": "2025-12-01T00:00:00Z",
    "description": "Narya",
    "amount": 1500.00,
    "category": "Gifts",
    "notes": "Christmas present"
}

###

POST http://localhost:8080/api/transactions
content-type: application/json

{
    "date": "2025-10-17T00:00:00Z",
    "description": "Apples",
    "amount": 3.50,
    "category": "Groceries",
    "notes": ""
}

###

POST http://localhost:8080/api/transactions
content-type: application/json

{
    "date": "2025-11-30T00:00:00Z",
    "description": "Bananas",
    "amount": 4.00,
    "category": "Groceries",
    "notes": ""
}

###

GET http://localhost:8080/api/budgets

###

GET http://localhost:8080/api/budgets/1

###

POST http://localhost:8080/api/budgets
content-type: application/json

{
    "target_amount": 50.00,
    "time_period": "weekly",
    "start_date": "2025-12-01T00:00:00Z",
    "category_id": 2
}

###

PUT http://localhost:8080/api/budgets/1
content-type: application/json

{
    "target_amount": 60.00,
    "time_period": "weekly",
    "start_date": "2025-12-01T00:00:00Z",
    "category_id": 1,
    "notes": "This is where the fun begins"
}

###

DELETE http://localhost:8080/api/budgets/1

###

GET http://localhost:8080/api/categories/1/spending

###

GET http://localhost:8080/api/categories/1/spending?period_start=2025-10-16&period_end=2025-10-17

###

GET http://localhost:8080/api/budgets/1/status