-- +goose Up
-- +goose StatementBegin
CREATE TYPE period AS ENUM (
    'weekly', 'monthly', 'bi-monthly', 'quarterly', 'yearly'
);

CREATE TABLE budgets(
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_amount FLOAT NOT NULL,
    time_period period NOT NULL,
    start_date DATE NOT NULL,
    notes TEXT,

    category_id INT NOT NULL UNIQUE,
    CONSTRAINT fk_category_id
    FOREIGN KEY (category_id)
    REFERENCES categories (id)
    ON DELETE CASCADE
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE budgets;

DROP TYPE IF EXISTS period CASCADE;
-- +goose StatementEnd
