-- +goose Up
-- +goose StatementBegin
CREATE TABLE categories(
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL
);

ALTER TABLE transactions
ADD COLUMN category_id INT NOT NULL;

INSERT INTO categories (name)
SELECT DISTINCT category FROM transactions;

UPDATE transactions
SET category_id = categories.id FROM categories
WHERE transactions.category = categories.name;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE transactions
DROP COLUMN category_id;

DROP TABLE categories;
-- +goose StatementEnd
