name: Continuous Delivery

on:
  pull_request:
    types: [closed]
    branches:
      - main
    
jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ledger:latest
          
      - name: Verify image on Docker Hub
        run: echo "Image ${{ secrets.DOCKERHUB_USERNAME }}/ledger:latest pushed to Docker Hub"