name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: ''
          POSTGRES_DB: ledger
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Version check
        run: go version

      - name: Install dependencies
        run: go mod tidy

      - name: Create config file
        run: |
          echo "{\"DbConnectionString\": \"postgres://runner:@localhost:5432/ledger\"}" > config.json
      
      - name: Check file content
        run: cat config.json

      - name: Integration tests
        run: go test ./...