name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Version check
        run: go version

      - name: Create JSON file
        run: |
          echo "{\"DbConnectionString\": \"postgres://runner:@localhost:5432/ledger\"}" > config.json
      
      - name: Check file content
        run: cat config.json

      - name: Integration tests
        run: go test ./...