name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ledger
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Version check
        run: go version

      - name: Install dependencies
        run: go mod tidy

      - name: Configure environment
        run: |
          echo "{\"DbConnectionString\": \"postgres://runner:postgres@127.0.0.1:5432/ledger\"}" > config.json
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
      
      - name: Check file content
        run: cat config.json

      - name: Wait for PostgreSQL
        run: |
          echo "Waiting for PostgreSQL..."
          for i in $(seq 1 10); do
            nc -z 127.0.0.1 5432 && echo "PostgreSQL is ready!" && exit 0
            echo "Waiting... ($i/10)"
            sleep 1
          done
          echo "PostgreSQL did not become ready."
          exit 1

      - name: Integration tests
        env:
          DATABASE_URL: postgres://runner:postgres@127.0.0.1:5432/ledger?sslmode=disable
        run: go test ./...